// @ts-check
// <reference types="@actions/github-script" />

const { getErrorMessage } = require("./error_helpers.cjs");
const { EXPIRATION_PATTERN, extractExpirationDate } = require("./ephemerals.cjs");
const { closeIssue } = require("./close_entity_helpers.cjs");

/**
 * Maximum number of issues to update per run
 */
const MAX_UPDATES_PER_RUN = 100;

/**
 * Delay between GraphQL API calls in milliseconds to avoid rate limiting
 */
const GRAPHQL_DELAY_MS = 500;

/**
 * Delay execution for a specified number of milliseconds
 * @param {number} ms - Milliseconds to delay
 * @returns {Promise<void>}
 */
function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Search for open issues with expiration markers
 * @param {any} github - GitHub GraphQL instance
 * @param {string} owner - Repository owner
 * @param {string} repo - Repository name
 * @returns {Promise<{issues: Array<{id: string, number: number, title: string, url: string, body: string, createdAt: string}>, stats: {pageCount: number, totalScanned: number}}>}
 */
async function searchIssuesWithExpiration(github, owner, repo) {
  const issues = [];
  let hasNextPage = true;
  let cursor = null;
  let pageCount = 0;
  let totalScanned = 0;

  core.info(`Starting GraphQL search for open issues in ${owner}/${repo}`);

  while (hasNextPage) {
    pageCount++;
    core.info(`Fetching page ${pageCount} of open issues (cursor: ${cursor || "initial"})`);

    const query = `
      query($owner: String!, $repo: String!, $cursor: String) {
        repository(owner: $owner, name: $repo) {
          issues(first: 100, after: $cursor, states: [OPEN]) {
            pageInfo {
              hasNextPage
              endCursor
            }
            nodes {
              id
              number
              title
              url
              body
              createdAt
            }
          }
        }
      }
    `;

    const result = await github.graphql(query, {
      owner: owner,
      repo: repo,
      cursor: cursor,
    });

    if (!result || !result.repository || !result.repository.issues) {
      core.warning(`GraphQL query returned no data at page ${pageCount}`);
      break;
    }

    const nodes = result.repository.issues.nodes || [];
    totalScanned += nodes.length;
    core.info(`Page ${pageCount}: Retrieved ${nodes.length} open issues (total scanned: ${totalScanned})`);

    let agenticCount = 0;
    let withExpirationCount = 0;

    // Filter for issues with agentic workflow markers and expiration comments
    for (const issue of nodes) {
      // Check if created by an agentic workflow (body contains "> AI generated by" at start of line)
      const agenticPattern = /^> AI generated by/m;
      const isAgenticWorkflow = issue.body && agenticPattern.test(issue.body);

      if (isAgenticWorkflow) {
        agenticCount++;
      }

      if (!isAgenticWorkflow) {
        continue;
      }

      // Check if has expiration marker with checked checkbox
      const match = issue.body ? issue.body.match(EXPIRATION_PATTERN) : null;

      if (match) {
        withExpirationCount++;
        core.info(`  Found issue #${issue.number} with expiration marker: "${match[1]}" - ${issue.title}`);
        issues.push(issue);
      }
    }

    core.info(`Page ${pageCount} summary: ${agenticCount} agentic issues, ${withExpirationCount} with expiration markers`);

    hasNextPage = result.repository.issues.pageInfo.hasNextPage;
    cursor = result.repository.issues.pageInfo.endCursor;
  }

  core.info(`Search complete: Scanned ${totalScanned} issues across ${pageCount} pages, found ${issues.length} with expiration markers`);
  return {
    issues,
    stats: {
      pageCount,
      totalScanned,
    },
  };
}

/**
 * Validate issue creation date
 * @param {string} createdAt - ISO 8601 creation date
 * @returns {boolean} True if valid
 */
function validateCreationDate(createdAt) {
  const creationDate = new Date(createdAt);
  return !isNaN(creationDate.getTime());
}

/**
 * Add comment to a GitHub Issue using REST API
 * @param {any} github - GitHub REST instance
 * @param {string} owner - Repository owner
 * @param {string} repo - Repository name
 * @param {number} issueNumber - Issue number
 * @param {string} message - Comment body
 * @returns {Promise<any>} Comment details
 */
async function addIssueComment(github, owner, repo, issueNumber, message) {
  const result = await github.rest.issues.createComment({
    owner: owner,
    repo: repo,
    issue_number: issueNumber,
    body: message,
  });

  return result.data;
}

async function main() {
  const owner = context.repo.owner;
  const repo = context.repo.repo;

  core.info(`Searching for expired issues in ${owner}/${repo}`);

  // Search for issues with expiration markers
  const { issues: issuesWithExpiration, stats: searchStats } = await searchIssuesWithExpiration(github, owner, repo);

  if (issuesWithExpiration.length === 0) {
    core.info("No issues with expiration markers found");

    // Write summary even when no issues found
    let summaryContent = `## Expired Issues Cleanup\n\n`;
    summaryContent += `**Scanned**: ${searchStats.totalScanned} issues across ${searchStats.pageCount} page(s)\n\n`;
    summaryContent += `**Result**: No issues with expiration markers found\n`;
    await core.summary.addRaw(summaryContent).write();

    return;
  }

  core.info(`Found ${issuesWithExpiration.length} issue(s) with expiration markers`);

  // Check which issues are expired
  const now = new Date();
  core.info(`Current date/time: ${now.toISOString()}`);
  const expiredIssues = [];
  const notExpiredIssues = [];

  for (const issue of issuesWithExpiration) {
    core.info(`Processing issue #${issue.number}: ${issue.title}`);

    // Validate creation date
    if (!validateCreationDate(issue.createdAt)) {
      core.warning(`  Issue #${issue.number} has invalid creation date: ${issue.createdAt}, skipping`);
      continue;
    }
    core.info(`  Creation date: ${issue.createdAt}`);

    // Extract and validate expiration date
    const expirationDate = extractExpirationDate(issue.body);
    if (!expirationDate) {
      core.warning(`  Issue #${issue.number} has invalid expiration date format, skipping`);
      continue;
    }
    core.info(`  Expiration date: ${expirationDate.toISOString()}`);

    // Check if expired
    const isExpired = now >= expirationDate;
    const timeDiff = expirationDate.getTime() - now.getTime();
    const daysUntilExpiration = Math.floor(timeDiff / (1000 * 60 * 60 * 24));
    const hoursUntilExpiration = Math.floor(timeDiff / (1000 * 60 * 60));

    if (isExpired) {
      const daysSinceExpiration = Math.abs(daysUntilExpiration);
      const hoursSinceExpiration = Math.abs(hoursUntilExpiration);
      core.info(`  ✓ Issue #${issue.number} is EXPIRED (expired ${daysSinceExpiration} days, ${hoursSinceExpiration % 24} hours ago)`);
      expiredIssues.push({
        ...issue,
        expirationDate: expirationDate,
      });
    } else {
      core.info(`  ✗ Issue #${issue.number} is NOT expired (expires in ${daysUntilExpiration} days, ${hoursUntilExpiration % 24} hours)`);
      notExpiredIssues.push({
        ...issue,
        expirationDate: expirationDate,
      });
    }
  }

  core.info(`Expiration check complete: ${expiredIssues.length} expired, ${notExpiredIssues.length} not yet expired`);

  if (expiredIssues.length === 0) {
    core.info("No expired issues found");

    // Write summary when no expired issues
    let summaryContent = `## Expired Issues Cleanup\n\n`;
    summaryContent += `**Scanned**: ${searchStats.totalScanned} issues across ${searchStats.pageCount} page(s)\n\n`;
    summaryContent += `**With expiration markers**: ${issuesWithExpiration.length} issue(s)\n\n`;
    summaryContent += `**Expired**: 0 issues\n\n`;
    summaryContent += `**Not yet expired**: ${notExpiredIssues.length} issue(s)\n`;
    await core.summary.addRaw(summaryContent).write();

    return;
  }

  core.info(`Found ${expiredIssues.length} expired issue(s)`);

  // Limit to MAX_UPDATES_PER_RUN
  const issuesToClose = expiredIssues.slice(0, MAX_UPDATES_PER_RUN);

  if (expiredIssues.length > MAX_UPDATES_PER_RUN) {
    core.warning(`Found ${expiredIssues.length} expired issues, but only closing the first ${MAX_UPDATES_PER_RUN}`);
    core.info(`Remaining ${expiredIssues.length - MAX_UPDATES_PER_RUN} expired issues will be closed in the next run`);
  }

  core.info(`Preparing to close ${issuesToClose.length} issue(s)`);

  let closedCount = 0;
  const closedIssues = [];
  const failedIssues = [];

  for (let i = 0; i < issuesToClose.length; i++) {
    const issue = issuesToClose[i];

    core.info(`[${i + 1}/${issuesToClose.length}] Processing issue #${issue.number}: ${issue.url}`);

    try {
      const closingMessage = `This issue was automatically closed because it expired on ${issue.expirationDate.toISOString()}.`;

      // Add comment first
      core.info(`  Adding closing comment to issue #${issue.number}`);
      await addIssueComment(github, owner, repo, issue.number, closingMessage);
      core.info(`  ✓ Comment added successfully`);

      // Then close the issue as not planned
      core.info(`  Closing issue #${issue.number} as not planned`);
      await closeIssue(github, owner, repo, issue.number, { state_reason: "not_planned" });
      core.info(`  ✓ Issue closed successfully`);

      closedIssues.push({
        number: issue.number,
        url: issue.url,
        title: issue.title,
      });

      closedCount++;
      core.info(`✓ Successfully processed issue #${issue.number}: ${issue.url}`);
    } catch (error) {
      core.error(`✗ Failed to close issue #${issue.number}: ${getErrorMessage(error)}`);
      core.error(`  Error details: ${JSON.stringify(error, null, 2)}`);
      failedIssues.push({
        number: issue.number,
        url: issue.url,
        title: issue.title,
        error: getErrorMessage(error),
      });
      // Continue with other issues even if one fails
    }

    // Add delay between GraphQL operations to avoid rate limiting (except for the last item)
    if (i < issuesToClose.length - 1) {
      core.info(`  Waiting ${GRAPHQL_DELAY_MS}ms before next operation...`);
      await delay(GRAPHQL_DELAY_MS);
    }
  }

  // Write comprehensive summary
  let summaryContent = `## Expired Issues Cleanup\n\n`;
  summaryContent += `**Scan Summary**\n`;
  summaryContent += `- Scanned: ${searchStats.totalScanned} issues across ${searchStats.pageCount} page(s)\n`;
  summaryContent += `- With expiration markers: ${issuesWithExpiration.length} issue(s)\n`;
  summaryContent += `- Expired: ${expiredIssues.length} issue(s)\n`;
  summaryContent += `- Not yet expired: ${notExpiredIssues.length} issue(s)\n\n`;

  summaryContent += `**Closing Summary**\n`;
  summaryContent += `- Successfully closed: ${closedCount} issue(s)\n`;
  if (failedIssues.length > 0) {
    summaryContent += `- Failed to close: ${failedIssues.length} issue(s)\n`;
  }
  if (expiredIssues.length > MAX_UPDATES_PER_RUN) {
    summaryContent += `- Remaining for next run: ${expiredIssues.length - MAX_UPDATES_PER_RUN} issue(s)\n`;
  }
  summaryContent += `\n`;

  if (closedCount > 0) {
    summaryContent += `### Successfully Closed Issues\n\n`;
    for (const closed of closedIssues) {
      summaryContent += `- Issue #${closed.number}: [${closed.title}](${closed.url})\n`;
    }
    summaryContent += `\n`;
  }

  if (failedIssues.length > 0) {
    summaryContent += `### Failed to Close\n\n`;
    for (const failed of failedIssues) {
      summaryContent += `- Issue #${failed.number}: [${failed.title}](${failed.url}) - Error: ${failed.error}\n`;
    }
    summaryContent += `\n`;
  }

  if (notExpiredIssues.length > 0 && notExpiredIssues.length <= 10) {
    summaryContent += `### Not Yet Expired\n\n`;
    for (const notExpired of notExpiredIssues) {
      const timeDiff = notExpired.expirationDate.getTime() - now.getTime();
      const days = Math.floor(timeDiff / (1000 * 60 * 60 * 24));
      const hours = Math.floor(timeDiff / (1000 * 60 * 60)) % 24;
      summaryContent += `- Issue #${notExpired.number}: [${notExpired.title}](${notExpired.url}) - Expires in ${days}d ${hours}h\n`;
    }
  } else if (notExpiredIssues.length > 10) {
    summaryContent += `### Not Yet Expired\n\n`;
    summaryContent += `${notExpiredIssues.length} issue(s) not yet expired (showing first 10):\n\n`;
    for (let i = 0; i < 10; i++) {
      const notExpired = notExpiredIssues[i];
      const timeDiff = notExpired.expirationDate.getTime() - now.getTime();
      const days = Math.floor(timeDiff / (1000 * 60 * 60 * 24));
      const hours = Math.floor(timeDiff / (1000 * 60 * 60)) % 24;
      summaryContent += `- Issue #${notExpired.number}: [${notExpired.title}](${notExpired.url}) - Expires in ${days}d ${hours}h\n`;
    }
  }

  await core.summary.addRaw(summaryContent).write();

  core.info(`Successfully closed ${closedCount} expired issue(s)`);
}

module.exports = { main };
